/*author table*/
DROP TABLE IF EXISTS `author`;
CREATE TABLE `author` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(255) NOT NULL,
  `DESCRIPTION` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*image table*/
DROP TABLE IF EXISTS `image`;
CREATE TABLE `image` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `IMAGE_KEY` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*music table*/
DROP TABLE IF EXISTS `music`;
CREATE TABLE `music` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `CATEGORY_ID` INT(10) UNSIGNED NOT NULL,
  `AUTHOR_ID` INT(10) UNSIGNED NOT NULL,
  `TITLE` VARCHAR(255) NOT NULL,
  `MUSIC_KEY` VARCHAR(255) NOT NULL,
  `UPDATE_TIMESTAMP` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*music category table*/
DROP TABLE IF EXISTS `music_category`;
CREATE TABLE `music_category` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `TITLE` VARCHAR(255) NOT NULL,
  `DESCRIPTION` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*video table*/
DROP TABLE IF EXISTS `video`;
CREATE TABLE `video` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `IMAGE_ID` INT(10) UNSIGNED NOT NULL,
  `AUTHOR_ID` INT(10) UNSIGNED NOT NULL,
  `TITLE` VARCHAR(255) NOT NULL,
  `VIDEO_KEY` VARCHAR(255) NOT NULL,
  `IMAGE_KEY` VARCHAR(255) NOT NULL,
  `UPDATE_TIMESTAMP` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*video category table*/
DROP TABLE IF EXISTS `video_category`;
CREATE TABLE `video_category` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `TITLE` VARCHAR(255) NOT NULL,
  `DESCRIPTION` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;