DROP TABLE IF EXISTS `music`;
CREATE TABLE `music` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `CATEGORY_ID` INT(10) UNSIGNED NOT NULL,
  `AUTHOR_ID` INT(10) UNSIGNED NOT NULL,
  `TITLE` VARCHAR(255) NOT NULL,
  `MUSIC_KEY` VARCHAR(255) NOT NULL,
  `UPDATE_TIMESTAMP` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;