DROP TABLE IF EXISTS `video`;
CREATE TABLE `video` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `IMAGE_ID` INT(10) UNSIGNED NOT NULL,
  `AUTHOR_ID` INT(10) UNSIGNED NOT NULL,
  `TITLE` VARCHAR(255) NOT NULL,
  `VIDEO_KEY` VARCHAR(255) NOT NULL,
  `IMAGE_KEY` VARCHAR(255) NOT NULL,
  `UPDATE_TIMESTAMP` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;